const Pp1 = {
  char: 0,
  x: 60,
  xc: 0,
  yc: 0,
  y: 250,
  yc: 0,
  size: 3,
  w: 0,
  h: 0,
  velX: 0,
  velY: 0,
  inventory: [],
  room: 0,
  hp: 20,
  look: "R",
  G: -2,
  SpX: 0,
  SpY: 0,
  xi: 0,
  yi: 0,
  frame: 0,
  lstDir: "R",
  breath: 0,
};
/*plot:-
the player sees the day get colder and darker than he had ever seen before,
the sun at noon today is to that of the sunrise of the latter days,
upon further inspection he witnessed,
that mist is tainting the sky,
obscuring all sunlight where crops and animals arise or sleep to 
which imbalances the ecosytem he's in,
the mist is comming from beyond the forest,
aided by his notebook,he grabs his sturdy axe and rifle,
 and a tent and embarks on a journey to find who did this,
 and end the misery of the forest*/
